### ISSUE TITLE
KeyType Invalid

### ISSUE THREAD

**Issue by pablo4lvarez** [GoogleCloudPlatform/recaptcha-enterprise-react-native#18]
Hey! What does that error means? I can't find anywhere that error explanation.
I'm passing a SiteKey just as the example in the documentation: 
```javascript
await initClient(siteKey, 5000)
          .then(() => setInitResult('ok'))
          .catch((error) => {
            setInitResult(error.toString());
            reject(error);
          });
```

Where siteKey is a string.

Thanks in advance! 🙏 

### Versions
* React Native -> 0.72.4
* Kotlin -> 1.8.0

**Comment by mcorner** [comment]
Either you are using an iOS key on Android or vice versa. Or perhaps you are trying to use an Android onplay key on a non GMSCore device.
