### ISSUE TITLE
key type invalid

### ISSUE THREAD

**Issue by maryjenel** [GoogleCloudPlatform/recaptcha-enterprise-react-native#24]
hi, 
I have two keys one for android and one for ios. The ios one works fine, but when initializing android i get this error:
` Error: Key type invalid`

I double checked my Android Package id and set it to the one in my gradle file. Should be including any other Android packages?

I set up the keys the same for both android and ios in  console.cloud.google.com

**Comment by walterjgsp** [comment]
Hi @maryjenel, thanks for reaching out to us. Is your app available to be used in an environment without play store? If so you need to have that configured as stated here https://cloud.google.com/recaptcha-enterprise/docs/create-key-mobile.

> If you want to create a key for an application that is available on other app stores in addition to the Google Play Store, turn on Support applications distributed outside of the Google Play Store.

For us to investigate this further to check if there's a problem from our side could you fill this form [recaptcha-mobile](https://forms.gle/sThtVbNBwPh2kVfb9), please?

**Comment by mcorner** [comment]
Since we haven't heard back on this issue we will close it.
