### ISSUE TITLE
reCAPTCHA Enterprise  score is always 0.1

### ISSUE THREAD

**Issue by Mynini** [GoogleCloudPlatform/recaptcha-enterprise-react-native#34]
My react-native project seems to have integrated recaptcha-enterprise-react-native successfully, and I can get token normally, but there are two problems.
Question1: I see that other people's access to successful projects will show a privacy-terms of use icon, but mine does not.  Look at the sample picture
<img width="432" alt="image" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-react-native/assets/24352270/0746007c-a172-4a76-84ac-17ada04e2e34">
Question 2: the score returned after I got the token and sent it to the background for verification has been 0.1, which bothers me.

I guess there may be three reasons:
Reason 1 is that I used vpn, (but this should be excluded, it is normal to send token to the backend score returned after the same web project is connected).
Reason 2: there is a problem with plug-in access.
There is a problem with the configuration of the 3:goole cloud project. I looked for a lot of information and didn't find out how to solve it, and reason 2 didn't seem to have a problem. Ask for help  !!!!!!!!!!!!

To be clear: I will execute.
After the 
   yarn add @ google-cloud/recaptcha-enterprise-react-native command,
 I found that the plug-in did not automatically link, 
so I executed a react-native @ google-cloud/recaptcha-enterprise-react-native manual link for android. 
but ios is not work,sor I add some code in ios podfile

The modified  file after execution is as follows
<img width="1308" alt="image" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-react-native/assets/24352270/69c1a8ef-f8b1-4c2c-9949-ba4451b7c53b">
<img width="991" alt="image" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-react-native/assets/24352270/5d822bf1-b388-4c6d-9c67-5ad919dc2a50">

<img width="1234" alt="image" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-react-native/assets/24352270/ff4ab120-8777-427d-ba14-5c66a0826537">

platform:
mac m1 14.4.1 
react-native: 0.68.5
"@google-cloud/recaptcha-enterprise-react-native": "^18.5.0-beta02"

**Comment by walterjgsp** [comment]
We don't offer score support in this channel, please refer to other channels to deal with this specific issue. One example is https://support.google.com/recaptcha/?hl=en and https://developers.google.com/recaptcha/docs/faq
