### ISSUE TITLE
iOS - Issue building app. Module `RecaptchaInterop` not found

### ISSUE THREAD

**Issue by vabruzzese** [GoogleCloudPlatform/recaptcha-enterprise-react-native#39]
## Background

Hello,

I'm having issues building my app with the latest release of this library.
```
"@google-cloud/recaptcha-enterprise-react-native": "^18.5.1",
```

I have followed the troubleshooting steps for iOS in the guide by setting the following configurations in my Podfile:
```
flipper_config = FlipperConfiguration.disabled
use_frameworks! :linkage => :static
```

The issue I'm receiving is the following:
```
Module 'RecaptchaInterop` not found
```

In my Podfile.lock I can see that the depedency is present:
```
  - recaptcha-enterprise-react-native (18.5.1):
    - glog
    - RCT-Folly (= 2022.05.16.00)
    - React-Core
    - RecaptchaEnterprise (= 18.5.1)
  - RecaptchaEnterprise (18.5.1):
    - RecaptchaInterop (~> 100.0.0)
  - RecaptchaInterop (100.0.0)
```

Do you know what might be the issue here? 

I have a suspicion that the `@import RecaptchaInterop;` in the build header is being called outside of the `__HAS_RECAPTCHA_INTEROP_FRAMEWORK__` flag. Perhaps this should be inside the `#define` block?

![Screenshot 2024-06-17 at 1 31 01 PM](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-react-native/assets/11095678/4c0dbb4c-76c9-472f-9289-a1ff252d83f1)

I looked into the source code of this project but I cannot see where this declaration is made. It seems like it is generated during the build step.

**Comment by mcorner** [comment]
possibly related: https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/issues/112

What version of XCode are you using?

**Comment by mcorner** [comment]
yes, the newest SDKs require at least 15.3

**Comment by vabruzzese** [comment]
> yes, the newest SDKs require at least 15.3

Understood, thank you. I will look into upgrading our project to the latest Xcode.

**Comment by dharaspatel** [comment]
I'm on 15.4 and having the same problem :(
