### ISSUE TITLE
React Native iOS facing the error while pod install file: undefined local variable or method `min_ios_version_supported' for module Pod.

### ISSUE THREAD

**Issue by chirag-blueed** [GoogleCloudPlatform/recaptcha-enterprise-react-native#44]
[!] Failed to load 'recaptcha-enterprise-react-native' podspec: 
[!] Invalid `recaptcha-enterprise-react-native.podspec` file: undefined local variable or method `min_ios_version_supported' for module Pod.

 #  from /Users/****/node_modules/@google-cloud/recaptcha-enterprise-react-native/recaptcha-enterprise-react-native.podspec:14
 #  -------------------------------------------
 #  
 >    s.platforms    = { :ios => min_ios_version_supported }
 #    s.source       = { :git => "https://github.com/GoogleCloudPlatform/recaptcha-enterprise-react-native.git", :tag => "#{s.version}" }
 #  -------------------------------------------
 
 
With the latest version 18.5.1, this issue is happening

**Comment by mcorner** [comment]
@chirag-blueed if this didn't get resolved on your end, please reopen

**Comment by oddlyspaced** [comment]
Hi, I am facing the same issue currently.

I added the package with yarn 
`yarn add @google-cloud/recaptcha-enterprise-react-native`

and on running pod install, it shows the following error :
```

[!] Invalid `Podfile` file:
[!] Invalid `recaptcha-enterprise-react-native.podspec` file: undefined local variable or method `min_ios_version_supported' for module Pod.

```
