### ISSUE TITLE
Fraud prevention assesment isnt triggered 

### ISSUE THREAD

**Issue by mohamedmaged** [GoogleCloudPlatform/recaptcha-enterprise-react-native#46]
while using this library fraud prevention didnt work on both android and IOS 
even thought transactionData is supplied to create assesment  method 

I really don't whether  the problem is with this library or the google backend side

**Comment by mohamedmaged** [comment]
@walterjgsp Nope there is an option to in google recaptcha enterprise to get Fraud assessment of a transaction using Recaptcha Token i use the token to create assesment and send other details about the transaction like card details and user details [ currently all tokens i generated from this library on both IOS and Android ] aren't working but the recpatcha tokens I create from the web integration it works 

I have create a case with Google support  Case 53445136 it should be now with the engineering team 
please let me know if you want more details

**Comment by walterjgsp** [comment]
Thanks for answering fast @mohamedmaged, creating a Google Support case it's the best way to ask for support related to scoring and assessment issues.

**Comment by mohamedmaged** [comment]
noted @walterjgsp  so I will close this issue :") have a nice day
